apiVersion: mirror.plugin.fluxcd.io/v1beta1
kind: Config
artifacts:
  - source: ghcr.io/stefanprodan/charts/podinfo
    destination: localhost:5050/charts/podinfo
    selector:
      semver: ">=6.9.0"
      limit: 3
    includeReferrers: true
  - source: ghcr.io/stefanprodan/manifests/podinfo
    destination: localhost:5050/manifests/podinfo
    selector:
      regex:
        pattern: "^latest$"
      sortBy: alphabetical
      limit: 1
    includeReferrers: true
    overwrite: true
  - source: docker.io/stefanprodan/podinfo
    destination: localhost:5050/podinfo
    selector:
      semver: "6.x"
      limit: 2
    includeReferrers: true
    verify:
      provider: cosign
      minAge: 24h
      matchOIDCIdentity:
        - issuer: https://token.actions.githubusercontent.com
          subject: ^https://github\.com/stefanprodan/.*$
